services:

  config-server:
    build:
      context: ./config-server
    container_name: config-server
    ports:
      - "8881:8881"

  service-registry:
    build:
      context: ./service-registry   # Make sure this folder exists
    container_name: service-registry
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
      - config-server

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8100:8100"
    depends_on:
      - service-registry

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8200:8200"
    depends_on:
      - service-registry

  inventory-service:
    build:
      context: ./inventory-service
    container_name: inventory-service
    ports:
      - "8300:8300"
    depends_on:
      - service-registry

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "9003:9003"
    depends_on:
      - service-registry

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    ports:
      - "8400:8400"
    depends_on:
      - service-registry
